### ISSUE TITLE
Add bit-based support

### ISSUE THREAD

**Issue by JakeWharton** [saket/file-size#11]
Transfer is usually measured in bits. For example, my 1Mbit Internet connection sounds nice, but how many MB is that actually?

**Comment by saket** [comment]
Will it be awkward if bits are represented by a class named `ByteSize`?

**Comment by saket** [comment]
Can do this. Will it be awkward if bits are represented by a class named `ByteSize`?

**Comment by JakeWharton** [comment]
Hmm I think I'd like to convince you that Si bytes, decimal bytes, and bits should all be separate inline classes around a Long 😁

**Comment by saket** [comment]
I think I'm convinced. I wasn't too happy with the IDE offering many similar-looking suggestions from the same `ByteSize` class -- a list that is only going to increase with the introduction of binary and decimal bits. It looks like I’ll end up with a hierarchy of types similar to the one present in your [byteunits](https://github.com/JakeWharton/byteunits/).

![Screenshot 2024-09-01 at 7 21 01 PM](https://github.com/user-attachments/assets/4166f3ad-2de6-4dd2-be64-602626428bc8)

**Comment by saket** [comment]
@JakeWharton was it an intentional decision not to offer both base-2 and base-10 units for bits in https://github.com/jakewharton/byteunits?

**Comment by JakeWharton** [comment]
I don't recall

**Comment by JakeWharton** [comment]
I think perhaps I just couldn't find anything using base 2 bit units.

**Comment by saket** [comment]
Got it, I'll do the same then. Can always add base 10 bit units afterwards.

**Comment by saket** [comment]
Got it, I'll do the same then. Can always add base 2 bit units afterwards.

**Comment by saket** [comment]
What do you think? https://github.com/saket/byte-size/releases/tag/2.0.0-beta02
