### ISSUE TITLE
Clarify that only SI-based units are supported and / or add support for power-of-two based units

### ISSUE THREAD

**Issue by sschuberth** [saket/file-size#9]
In addition to power-of-ten based "kilo", "mega", "giga" units, it would be nice to also support power-of-two based "kibi", "mebi", "gibi" IEC units, which are esp. common in Information Technology, see e.g. [multiple byte units](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units).

**Comment by SimonMarquis** [comment]
- #5

**Comment by saket** [comment]
Both SI and IEC units are now available in https://github.com/saket/byte-size/releases/tag/2.0.0-beta02
